/**
 * Generates `out/sw.js` after `next build`.
 *
 * The service worker precaches every file in the static export (app shell,
 * hashed _next/static chunks, fonts, icons, manifest) so the app works fully
 * offline. Precache entries are stored relative to the SW scope so the same
 * generated worker works under any basePath (`/open-writer/` on GitHub Pages,
 * `/` locally).
 *
 * Cache invalidation: the cache name embeds a build stamp. When the app is
 * rebuilt and redeployed, sw.js changes -> browser installs the new worker ->
 * activate() deletes the old cache. Hashed chunk names also change per build,
 * so stale entries are never served.
 *
 *   node scripts/generate-sw.mjs
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT_DIR = path.resolve(__dirname, "../out")

if (!fs.existsSync(path.join(OUT_DIR, "index.html"))) {
  console.error("out/index.html not found — run `bun run build` first.")
  process.exit(1)
}

const stamp = new Date().toISOString().replace(/[-:]/g, "").slice(0, 14) // YYYYMMDDHHMMSS
const CACHE = `open-writer-${stamp}`

function walk(dir, base = "") {
  const entries = []
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const name = ent.name
    const rel = path.posix.join(base, name)
    const abs = path.join(dir, name)
    if (name.startsWith(".")) continue
    if (name === "sw.js") continue // never precache ourselves
    if (ent.isDirectory()) {
      entries.push(...walk(abs, rel))
    } else if (name.endsWith(".html") && name !== "index.html" && name !== "404.html") {
      continue // other html pages not part of the shell
    } else {
      // relative to scope root, e.g. "_next/static/chunks/x.js", "icons/icon-192.png"
      entries.push(rel)
    }
  }
  return entries
}

const files = walk(OUT_DIR)
  .map((f) => f.replace(/\\/g, "/"))
  .sort()
const precache = files.map((f) => "./" + f)
precache.unshift("./index.html") // scope-root app shell (serves "/")

const body = `/* Generated by scripts/generate-sw.mjs — do not edit. */
const CACHE = ${JSON.stringify(CACHE)}
const PRECACHE = ${JSON.stringify(precache)}

// Resolve a scope-relative path against the SW's actual scope, so this works
// under /open-writer/ on GitHub Pages and / locally.
function toURL(p) {
  return new URL(p, self.registration.scope).href
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      Promise.allSettled(PRECACHE.map((p) => cache.add(toURL(p))))
    ).then(() => self.skipWaiting())
  )
})

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k.startsWith("open-writer-") && k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  )
})

self.addEventListener("fetch", (event) => {
  const req = event.request
  if (req.method !== "GET") return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return // never intercept cross-origin (GitHub API, AI)

  // Navigations: network-first, fall back to the cached app shell offline.
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone()
          caches.open(CACHE).then((c) => c.put(toURL("./index.html"), copy))
          return res
        })
        .catch(() =>
          caches.match(toURL("./index.html")).then((r) => r || caches.match(toURL("./404.html")))
        )
    )
    return
  }

  // Same-origin static assets: cache-first with background refresh.
  event.respondWith(
    caches.match(req).then((cached) => {
      const network = fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
          }
          return res
        })
        .catch(() => cached)
      return cached || network
    })
  )
})
`

fs.writeFileSync(path.join(OUT_DIR, "sw.js"), body)
console.log(`out/sw.js written (${precache.length} precache entries, cache ${CACHE})`)
